let FirstName = "Sumanth";
let LastName = "Tunga";
let Space = " ";
let hello = "Hello";
let myName = "My name is";
let FullName = "Sumanth Tunga";
console.log(FirstName + Space + LastName);
console.log("hello, My name is:", FirstName + Space + LastName);
console.log(hello + Space + myName + Space + FullName);
let Age = 26;
let CurrentYear = 2022;
console.log(CurrentYear - Age);
